create database dashboard

use dashboard

create table Users (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY (Id),
 Email NVARCHAR(256) UNIQUE NOT NULL,
 PasswordHash NVARCHAR(256) NOT NULL,
 Name NVARCHAR(150) NOT NULL,
 Role NVARCHAR(20) NOT NULL DEFAULT 'user',
 IsActive BIT NOT NULL DEFAULT 1,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
 UpdatedAt DATETIME2 NULL
)

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY (Id);